-- Schema for the tracks table

CREATE TABLE IF NOT EXISTS tracks (
    id VARCHAR(255) PRIMARY KEY, -- Unique identifier for the track
    artist_id VARCHAR(255) NOT NULL REFERENCES artist_profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Audio features (using JSONB for flexibility)
    audio_features JSONB, 
    -- Example structure:
    -- {
    --   "bpm": 120,
    --   "key": "C minor",
    --   "scale": "minor",
    --   "energy": 0.8,
    --   "danceability": 0.7,
    --   "valence": 0.6,
    --   "duration_ms": 180000,
    --   "time_signature": 4,
    --   "spectrogram_features": {...} -- Optional
    -- }

    -- Generation details
    generation_prompt_id VARCHAR(255), -- Link to the prompt used (if applicable)
    generation_metadata JSONB, -- Other metadata about generation (e.g., model version)

    -- Performance summary (using JSONB, updated by MetricsCollector)
    performance_summary JSONB 
    -- Example structure:
    -- {
    --   "total_streams": 15000,
    --   "engagement_rate": 0.15,
    --   "revenue_estimate": 50.00,
    --   "last_updated": "..."
    -- }
);

-- Index for faster lookups by artist_id
CREATE INDEX IF NOT EXISTS idx_tracks_artist_id ON tracks(artist_id);

-- Index for faster lookups by title
CREATE INDEX IF NOT EXISTS idx_tracks_title ON tracks(title);

-- Trigger to automatically update updated_at on row update
CREATE TRIGGER update_tracks_updated_at
BEFORE UPDATE ON tracks
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column(); -- Reuse function from artist_profiles.sql

COMMENT ON TABLE tracks IS 'Stores information about individual tracks generated by AI artists, including audio features and performance summaries.';
COMMENT ON COLUMN tracks.audio_features IS 'Flexible JSONB field for storing extracted audio features like BPM, key, energy, etc.';
COMMENT ON COLUMN tracks.performance_summary IS 'Flexible JSONB field summarizing the track\'s performance metrics, updated periodically.';

